osx_image: xcode10.2
language: objective-c
xcode_project: BlockTrackerSample
xcode_scheme: BlockTracker
xcode_sdk: iphoneos12.2
env:
  global:
  - FRAMEWORK_NAME=BlockTracker
  - secure: qnyHa+IOBMShGvuOBVDky2+izNiDXy0ctOnUBIlH5h7OI2/gvXJSaoI0D9BEiYLTIXGUBMwfjfu4vT2HUOTC0nqYKyPdoa8KipmyzEnCJGK9glCk18KUnn+ws22mwKA/hfiGfYEJ3hSDu9+Gx3HGROrakkW5uIJy/A7GZjqyVlYXHC9LQYtuOqo1rf6S6fJ5oROUPfUWGOeBcteN0/unuhWZ0n4rHDuu6zPWe2a7mBjw2v1NtqAV0meTwiP1lmB1gGWbvsA6V58ypDAJOt2hSVh71BUh04dF7EGbky9HZjPjT4nho7aNRcIJT32p06UOh9VV1v/NMhNXc2rAIKz2dA3R8K387FV81GqoGAmofhbFIsRYHVBr+elUvoy3N1ZpjKpufPhzfSS4vr7uCQAR9gJdoh1kwICiAXb+ocIlv1Wn4Ei76EOF1noSvxf/zGxZXoYIlis8UZyN0iZy6i8l6cD9J6pPP6qS+L5TMZn4cEDk/YUeJqtQWo1QOTbrcR2HumPJi/tqdNhYWRbv2EXGuip/+mU5jyDNufG3i52M0gXf1UnRhJxCPLy049cWmLb3Zq4to15/+XOwHdxt4BURBBQPybam2G4isGTob44jHpVWCIusiOmcveu4ohCldi3pTWGKGH3anWs71Xfa/AvkZeo2vghby9MeymOramL66h0=
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
before_script:
- carthage bootstrap
before_deploy:
- carthage build --no-skip-current
- carthage archive $FRAMEWORK_NAME
script: 
- xcodebuild -project BlockTrackerSample.xcodeproj -scheme "BlockTracker iOS" -configuration Release ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES build test
- xcodebuild -project BlockTrackerSample.xcodeproj -scheme "BlockTrackerSample macOS" -configuration Release ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES build test
deploy:
  provider: releases
  api_key:
    secure: zVxZe97VyxaZ3XyFgjG/9feAlhqJuheryGYuEUUkToZbt2ygUhItjmi4pVBWkwIK/iueUb8hDusJyv7knb4fzIDXw6w2b0aGqo1/9D4JBPiY2IB/94mCWs1aGdNpfDcQtHo9Powd7Izfb6NNCrE7CdIsExhNoHI5JQ5n7cWqTOggV02ibWYW9DNfgeEHYy0mCQyyHFhkEEcP5a7zZqTEcWJijLdJa1ytgWE1Nma3IyAO5hgs2kvP1ZKCxwehf767fN/+wxzQfQFupZo2KksM0cfGQVbvgkpTdzCk1Mm07vWFIxakwmPgZXv6S0OoU+gVZw2zaZobDDa8gt55u4BxtrEwFI0fWOgsff7Vg4a1B1xBEN8rW21bvnTLFmhsicI3dyif/6RXuMTIpp3tNr8YFaNt9D9OdgLZicjip0FnPFVPo+OVb1wJixaw79Wy43V5Lt79lD4Sfh75bM2fKQVVBTp3gD/Tg6O1amU6qRwp2Ld9JwPcYUsymiP7U+7qrpOXx0rymsB+eqkmPAUR4V1+Bv5fDpG3lEbgiJzYhxS4LnZ0weU5rHnOy+AODHxWFCzYvfK1Mx6WjYZN3aRt3JlRiHZYnyxFcEA6l41gl8h3WHNF9U7J1FZwtRyTUGeIn3aGVIg1VWSXaw/8M/jERiiTDYf5SQj3HIVEV4Ejt+6RStk=
  file: BlockTracker.framework.zip
  skip_cleanup: true
  on:
    repo: yulingtianxia/BlockTracker
    tags: true
